"use client"

import { Outfit } from "next/font/google";

import "./globals.css";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body
        className={`${outfitSans.variable} antialiased`}
      >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
